# Macro file for SuperSUN simulation
# when running in interactive mode
#/control/verbose 2
#/control/saveHistory
#/run/verbose 2#

#/vis/open
#/vis/scene/add/trajectories
#/vis/drawVolume
#/vis/scene/endOfEventAction accumulate

#/vis/viewer/set/viewpointVector -1 0 0
#/vis/viewer/set/lightsVector -1 0 0
#/vis/viewer/set/style wireframe
#/vis/viewer/set/auxiliaryEdge true
#/vis/viewer/set/lineSegmentsPerCircle 100

#/vis/scene/add/trajectories smooth
#/vis/scene/add/scale   # Simple scale line
#/vis/scene/add/axes    # Simple axes: x=red, y=green, z=blue.
# guide away from source, 90 deg bend, tube below chopper blades
# set the file of the starting spectrum
/gun/spectrumfile spec1.dat
# tube above chopper blades, tube to detector
#/det/optpot1 220
#/det/eta1 0.0001
#/det/diff1 0.0
# converter volume (INSIDE LIQUID HELIUM, therfore 18.5 neV reduced potential
#/det/optpot2 100
#/det/eta2 0.0001
#/det/diff2 0.0
# cube inside the converter. reduce by 18.5 because submerged in lHe
#/det/optpot3 230
#/det/eta3 0.0001
#/det/diff3 0.0
#end plugs of converter, reduce by 18.5neV becuase submerged in lHe
#/det/optpot4 230
#/det/eta4 0.0001
#/det/diff4 0.0

#shutter plug geometry height
/det/valveheight -200
# energy independent loss in helium
/mat/helifetime 300000000000
# neutron life time
/mat/nlifetime 88000000000
# foil loss cross section0
/mat/foil 0.000000000001
# number of steps before particle is artificially killed
/mat/numofsteps 10000000000
# file name of output from materialboundaryprocess
/mat/outputfile1 output31.txt
# use time steps to dump track information
/mat/outputfile2 snapshot.txt
# set time for timesteps in milliseconds. (if set to zero or commented out, no output is generated)
/mat/timesteps 0 # was 100
# set maximum step size for all source geometries (all the same)
/det/stepsize 100
# how many particles are run
/run/beamOn 100
